# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PMexample.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.powerButton = QtWidgets.QPushButton(self.centralwidget)
        self.powerButton.setGeometry(QtCore.QRect(260, 330, 221, 81))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.powerButton.setFont(font)
        self.powerButton.setObjectName("powerButton")
        self.powerLabel = QtWidgets.QLabel(self.centralwidget)
        self.powerLabel.setGeometry(QtCore.QRect(230, 170, 281, 91))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setKerning(False)
        self.powerLabel.setFont(font)
        self.powerLabel.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.powerLabel.setObjectName("powerLabel")
        self.pushButton_Nothing = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Nothing.setGeometry(QtCore.QRect(300, 470, 291, 81))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.pushButton_Nothing.setFont(font)
        self.pushButton_Nothing.setObjectName("pushButton_Nothing")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionNothing_here = QtWidgets.QAction(MainWindow)
        self.actionNothing_here.setObjectName("actionNothing_here")
        self.actionOr_here = QtWidgets.QAction(MainWindow)
        self.actionOr_here.setObjectName("actionOr_here")
        self.actionAfter_the_separator = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.actionAfter_the_separator.setFont(font)
        self.actionAfter_the_separator.setObjectName("actionAfter_the_separator")
        self.menuFile.addAction(self.actionNothing_here)
        self.menuFile.addAction(self.actionOr_here)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionAfter_the_separator)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.powerButton.setText(_translate("MainWindow", "Read Power"))
        self.powerLabel.setText(_translate("MainWindow", "No Power"))
        self.pushButton_Nothing.setText(_translate("MainWindow", "Nothing"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionNothing_here.setText(_translate("MainWindow", "Nothing here"))
        self.actionOr_here.setText(_translate("MainWindow", "Or here!"))
        self.actionAfter_the_separator.setText(_translate("MainWindow", "After the separator!"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
